name: Automated Code Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your test and build steps here
